# Generated by Django 5.1.1 on 2024-10-01 22:16

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=myapp.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
